spring:
  # 임시 메일. 실제 API로 변경할 예정
  mail:
    host: "smtp.gmail.com"
    port: 587
    properties:
      mail:
        smtp:
          connection-timeout: 5000
          auth: false
          starttls:
            enable: true
          ssl:
            enable: false
    username: ${SMTP_EMAIL}
    password: ${SMTP_PASSWORD}

  r2dbc:
    url: r2dbc:mysql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:3306/${DEFAULT_DATABASE}
    properties:
      ssl: true
      sslMode: VERIFY_IDENTITY

  application:
    name: e1i2-server

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

server:
  port: 8080

jwt:
  secretKey: "tmpSecretadsfsadfdsafasdfsadtmpSecretadsfsadfdsafasdfsadtmpSecretadsfsadfdsafasdfsadtmpSecretadsfsadfdsafasdfsad"