name: backend-CICD

on:
  push:
    branches:
      - "main"

env:
  version: ${{ github.sha }}
  docker_image_name: ${{ github.action_repository }}:${{ github.sha }}
  template_file_path: services/chart/values/${{ github.action_repository }}-values.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: gradle build
      run: |
        gradle build -x test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.docker_image_name }}
  
  
  update-argocd-metadata:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: e1i2/argocd
      - name: Check file existence
        id: check_values_exists
        uses: andstor/file-existence-action@v2
        with:
          files: ${{ env.template_file_path }}
      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          sudo sed -i '' 's/version\: .*/version\: ${{ env.version }}/g' services/chart/values/e1i2-server-values.yaml
      
      - name: create values.yaml
        uses: danielr1996/envsubst-action@1.0.0
        if: steps.check_files.outputs.files_exists == 'false'
        env:
            VERSION: ${{ github.sha }}
            NAME: feltpen-server
            PROFILE: live
            PORT: 8080
        with:
          input: values-template.yaml
          output: ${{ env.template_file_path }}
      - name: git push
        run: |
          git config --global user.email "GitHub Actions Bot@github.com"
          git config --global user.name "GitHub Actions Bot"
          git add ${{ env.template_file_path }}
          git commit -m "update template"
          git pull origin main
          git push origin main
